DATA_NEOSMARTBLINDS = "neosmartblinds"

CONF_DEVICE = "blind_code"
CONF_CLOSE_TIME = "close_time"
CONF_ID = "hub_id"
CONF_PROTOCOL = "protocol"
CONF_PORT = "port"

CMD_UP = "up"
CMD_DOWN = "dn"
CMD_MICRO_UP = "mu"
CMD_MICRO_DOWN = "md"
CMD_STOP = "sp"
CMD_FAV = "gp"
CMD_SET_FAV = "pp"
CMD_REVERSE = "rv"
CMD_CONFIRM = "sc"
CMD_LIMIT = "ld"
